### ISSUE TITLE
error with requirements

### ISSUE THREAD

**Issue by pouyapanah** [georgeliu233/Scene-Rep-Transformer#2]
Hello, I'd like to inquire about the required Python version and operating system to run your code. While attempting to install the listed requirements, I encountered errors related to dependencies and libraries.

**Comment by georgeliu233** [comment]
Hi there, the env is built on python 3.7 + ubuntu 20.08. There might be some compatible issues in setting up TF, SMARTS and CARLA altogether, so do let me know if you encounter new dependency  issues.
