### ISSUE TITLE
How to train?

### ISSUE THREAD

**Issue by zygalaxy** [georgeliu233/Scene-Rep-Transformer#5]
How should I train? I don't see the corresponding train.py

**Comment by 12jenny** [comment]
Have you solved the problem yet?

**Comment by Cyanopica321** [comment]
I also can't find the training code, have you solved it?

**Comment by 12jenny** [comment]
Not yet.

**Comment by georgeliu233** [comment]
Hi all,
Sorry for the late reply by other projects I am recently busy at!

Yes, currently the repo only contains the testing part of all algos, and I plan to collate the rest part of the project by the next couple of months when available. It is based on the original trainer from tf2rl.

Bset,
Haochen

**Comment by georgeliu233** [comment]
You may access the training pipelines in ```./envs/runners```, and full algorithm in ```./algos``` first, for your own development.

**Comment by 12jenny** [comment]
> Hi all, Sorry for the late reply by other projects I am recently busy at!
> 
> Yes, currently the repo only contains the testing part of all algos, and I plan to collate the rest part of the project by the next couple of months when available. It is based on the original trainer from tf2rl.
> 
> Bset, Haochen

And may I ask how your model was trained?

**Comment by georgeliu233** [comment]
Hi Jenny,

Pretty straightforward: 1) initialize env (smarts/carla) 2) initalize the algos as in ```./algo```, and 3) wrap both env and algo in the corresponding trainer (```./envs/runners```). call the trainer to train the model.

**Comment by 12jenny** [comment]
> Hi Jenny,
> 
> Pretty straightforward: 1) initialize env (smarts/carla) 2) initalize the algos as in `./algo`, and 3) wrap both env and algo in the corresponding trainer (`./envs/runners`). call the trainer to train the model.

Okay, thanks for the answer. I'll give it a try, wish me luck! Hopefully I can contact you afterwards!
