### ISSUE TITLE
can you provide detail  python environment info?

### ISSUE THREAD

**Issue by kaiixing** [georgeliu233/Scene-Rep-Transformer#6]
Hi, I'm using Ubuntu 20.04 and Python 3.8.10. I have tried many times but still can't succeed in doing 'pip -r requirements.txt'. Could you please post your environment information?
1.before split requirements  into  SMARTS and Scene-Rep-Transformer
```bash
(venv) de@pc# pip install  -r requirements.txt
ERROR: Double requirement given: matplotlib==3.4.2 (from -r requirements.txt (line 97)) (already in matplotlib==3.4.3 (from -r requirements.txt (line 4)), name='matplotlib')
```
2.split requirements ,just Scene-Rep-Transformer
```bash
(venv) de@pc# pip install  -r requirements.txt
ERROR: imageio 2.34.1 has requirement pillow>=8.3.2, but you'll have pillow 8.2.0 which is incompatible.
ERROR: scikit-image 0.21.0 has requirement pillow>=9.0.1, but you'll have pillow 8.2.0 which is incompatible.
ERROR: rich 13.7.1 has requirement typing-extensions<5.0,>=4.0.0; python_version < "3.9", but you'll have typing-extensions 3.7.4.3 which is incompatible.
ERROR: twisted 24.3.0 has requirement typing-extensions>=4.2.0, but you'll have typing-extensions 3.7.4.3 which is incompatible.
......
ERROR: tensorflow-gpu 2.4.0 has requirement numpy~=1.19.2, but you'll have numpy 1.24.4 which is incompatible.
ERROR: tf2rl 1.1.5 has requirement tensorflow-addons~=0.13.0, but you'll have tensorflow-addons 0.11.2 which is incompatible.
```
after I solve problem above,then 
```
(venv) de@pc# cd tools;python test.py  --scenario=left_turn  --algo=scene_rep
ModuleNotFoundError: No module named 'cv2'

```
I know it means I need to install opencv-python and there are many other dependent packages that should be installed. I tried to solve those packages one by one many times and failed. Could you help me? Thanks!

**Comment by georgeliu233** [comment]
Hi,
Sorry for the inconvenience. My dependency is mixed by other projrct and it is too long. Yes, it is likely to have package contradictions for this project due to some issues in earlier SMARTS development and the tensorflow.. You may first try to pass the sanity test or load the simulation scenarios for SMARTS or CARLA. Let me know for other package issues, all the best!
