### ISSUE TITLE
The Dataset ?

### ISSUE THREAD

**Issue by Andrea010725** [georgeliu233/Scene-Rep-Transformer#8]
Hi, I was wondering, what was the dataset you used to train Transformer?

**Comment by georgeliu233** [comment]
Hi,
For our method, the Transformer is trained along with the learning process with RL, so the data are collected online during interactions with the env.

**Comment by Andrea010725** [comment]
Thank you for your response. It's a really rewarding job. Can I ask another Q  Is the code for the scenario understanding part defined in modules/policy ?
